# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  lane :beta do
    get_certificates           # invokes cert
    get_provisioning_profile   # invokes sigh
    build_app
  end

  lane :create_app do	
​    produce
  end

 desc "Create ipa"
  lane :make_build do
    enable_automatic_code_signing
    increment_build_number
    gym
  end


lane :build_and_test do |options|
  target_name = options[:target_name]
  branch_name = options[:branch_name]
  version = options[:version]

  # Message to Telegram: Started building
  message = "Started building #{target_name} #{branch_name} #{version}"
  #telegram(message: message)

  # Build
  build_app

  # Run tests
  run_tests

  # Message to Telegram: Built
  message = "Built #{target_name} #{branch_name} #{version}"
  #telegram(message: message)
end


end
